sudo: required

language: java

services:
  - docker
  
before_install:
  - docker-compose build
  - docker-compose up -d couchtest
  - sleep 100

script:
  - ./mvnw clean package source:jar javadoc:jar
  - ./mvnw deploy
  - ./mvnw dockerfile:build
  - ./mvnw dockerfile:push
