sudo: required

language: java

services:
  - docker
  
#before_install:
  #- docker-compose build
  #- docker-compose up -d couchtest
  #- sleep 100

script:
  - cp ./dist/settings.xml $HOME/.m2/settings.xml
  - ./mvnw clean package -DskipTests source:jar javadoc:jar deploy 
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_USR" --password-stdin
  - ./mvnw dockerfile:build
  - ./mvnw dockerfile:push
