sudo: required

language: java

#services:
#  - docker
  
#before_install:
#  - docker-compose pull couchtest
#  - docker-compose build
#  - docker-compose up -d couchtest
#  - sleep 100
#  - docker-compose logs couchtest

install:
#  - cp ./dist/settings.xml $HOME/.m2/settings.xml
#  - ./mvnw -DskipTests source:jar javadoc:jar
#  - ./mvnw -DskipTests deploy
  - ./mvnw -DskipTests install -DcreateChecksum=true source:jar javadoc:jar
#  - ./mvnw dockerfile:build dockerfile:push

script:
  - echo "skipping tests"

deploy:
  provider: bintray
  file: "./bintray-old.json"
  user: "blablanumerodeux"
  key: $BINTRAY_API_KEY
  skip_cleanup: true # to upload artifacts created during the build
  on:
    all_branches: true

cache:
  directories:
    - $HOME/.m2