sudo: required

language: java

services:
  - docker
  
before_install:
  - docker-compose pull couchtest
  - docker-compose up -d couchtest
  - sleep 20

#install:
#  - cp ./dist/settings.xml $HOME/.m2/settings.xml
#  - ./mvnw -DskipTests source:jar javadoc:jar
#  - ./mvnw -DskipTests deploy
#  - ./mvnw deploy
#  - ./mvnw dockerfile:build dockerfile:push

