sudo: required

language: java

services:
  - docker
  
before_install:
  - docker-compose ps  
  - docker ps --all
  - docker build -f Dockerfile.testdb . -t testdb
  - docker images
  - sudo netstat -pna | grep 11211
  - docker ps
  - docker-compose down
  - docker-compose up couchtest
  - docker-compose logs couchtest
  - sleep 100
  - docker-compose logs couchtest
  
