sudo: required

language: java

services:
  - docker
  
before_install:
  - docker-compose build
  - docker-compose up -d couchtest
  - sleep 100

install:
  - cp ./dist/settings.xml $HOME/.m2/settings.xml
  - ./mvnw package -DskipTests source:jar javadoc:jar
#  - ./mvnw -DskipTests deploy
  - ./mvnw deploy
  - ./mvnw dockerfile:build dockerfile:push

