version: '3'
services:
  couchtest:
    image: "dakarinternational/couch-test:latest"
    build:
      dockerfile: Dockerfile.testdb
      context: .
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"
    container_name: "couch-test"
    networks:
      - dakar-network
  couch:
    image: "couchbase:5.1.0"
    ports:
      - "8091-8094:8091-8094"
      - "11210-11211:11210-11211"
    container_name: "couch-dakar"
    networks:
      - dakar-network
  app:
    image: "dakarinternational/dakar:latest"
    env_file: .env
    build:
      dockerfile: Dockerfile
      context: .
      args:
        JAR_FILE: $JAR_FILE
    ports:
     - "8080:8080"
    container_name: 'app-dakar'
    depends_on:
     - "couch"
    networks:
      - dakar-network
networks:
    dakar-network:
        driver: bridge
