# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    machine: true
#      image: circleci/classic:latest
      
#    docker:
#      - image: circleci/openjdk:8-jdk
#      - image: dakarinternational/couch-test:latest
        
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
#      - setup_remote_docker
#      - run: |
#          ulimit -c unlimited
#          ./dump
      #           tell the operating system to remove the file size limit on core dump files 

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: run test db
          command: |
            docker-compose pull couchtest
            docker-compose up -d couchtest
            docker-compose logs couchtest
      - run:
          name: maven install
          command: |
            sleep 50
            mvn install -DcreateChecksum=true source:jar javadoc:jar -e
            docker-compose stop couchtest
      - run:
          name: maven deploy
          command: |
            cp ./.circleci/settings.xml ~/.m2 
            mvn -DskipTests deploy
      - run:
          name: docker build
          command: |
            mvn dockerfile:build 
      - run:
          name: docker push
          command: |
            mvn dockerfile:push


  build-skiptest:
    docker:
      - image: circleci/openjdk:8-jdk
    
    steps:
      - checkout
#      - run: mkdir -p workspace
#      will be created here /home/circleci/project/workspace


      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: maven install
          command: |
            mvn install -DskipTests -DcreateChecksum=true source:jar javadoc:jar -e
            
      # Persist the specified paths (workspace/echo-output) into the workspace for use in downstream job. 
      - persist_to_workspace:
         root: /home/circleci/
         paths:
           - /home/circleci/project/target/maven-metadata-local.xml

  maven-deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: maven deploy
          command: |
            cp ./.circleci/settings.xml ~/.m2 
            mvn -DskipTests deploy
            
  docker-build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: docker build
          command: |
            mvn dockerfile:build 
            
            
  docker-push:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: docker push
          command: |
            mvn dockerfile:push
        
    
  ssh-deploy-in-vps:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run:
          name: deploy on vps
          command: |
            ls -lart
            ssh -oStrictHostKeyChecking=no dreaser@dakar.lambla.eu
      - add_ssh_keys:
          fingerprints:
            - "32:e4:94:57:e8:e3:04:a1:65:a7:a7:49:a7:e2:e8:56"
              
              
  build-and-push-testdb:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build and push
          command: |
            docker login -p $DOCKER_PWD -u $DOCKER_USR
            docker-compose build couchtest
            docker-compose push couchtest
            

  run-test-db:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: pull and run
          command: |
            docker-compose pull couchtest
            docker-compose up -d couchtest
            docker-compose logs -f couchtest



workflows:
  version: 2
  
  run-testdb:
    jobs:
      - hold:
          type: approval
      - run-test-db:
          requires:
            - hold
          
  just-build:
    jobs:
      - hold:
          type: approval
      - build:
          requires:
            - hold


  build-skiptest-deploy-push-vps:
    jobs:
      - hold:
          type: approval
      - build-and-push-testdb
#          requires:
#            - hold
      - build-skiptest:
          requires:
            - build-and-push-testdb
      - ssh-deploy-in-vps:
          requires:
            - build-skiptest
          filters:
            branches:
              only: features/circleci

  build-deploy-push-vps:
    jobs:
      - hold: 
          type: approval 
      - build-and-push-testdb:
          requires:
            - hold
      - build:
          requires:
            - build-and-push-testdb
      - ssh-deploy-in-vps:
          requires:
            - build
          filters:
            branches:
              only: features/circleci

