version: '3.1'

services:
  couch:
    image: "couchbase:5.1.0"
    ports:
      - "8091-8094:8091-8094"
      - "11210-11211:11210-11211"
    volumes:
      - couch:/opt/couchbase/var
    networks:
      - dakar-network
  app:
    image: "dakarinternational/dakar:latest"
    ports:
      - "8080:8080"
    depends_on:
      - "couch"
    networks:
      - dakar-network
    environment:
      PROFILE: prod
  app-ng:
    image: "dakarinternational/dakar-ng:latest"
    ports:
      - "80:80"
    depends_on:
      - "app"
    networks:
      - dakar-network

networks:
  dakar-network:
    driver: overlay
    external: false

volumes:
  couch:
    driver: local
    driver_opts:
      type: none
      device: /opt/couchbase/node1/var
      o: bind
