version: '3.1'

services:
  couch:
    image: "couchbase:5.1.0"
    volumes:
      - couch:/opt/couchbase/var
    networks:
      - dakar-network

  api:
    image: "dakarinternational/dakar:latest"
    depends_on:
      - "couch"
    networks:
      - dakar-network
    environment:
      PROFILE: prod

  front:
    image: "dakarinternational/dakar-ng:latest"
    depends_on:
      - "dakar-api"
    networks:
      - dakar-network
      - traefik_traefik
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dakar-front.rule=Host(`dakar.project.lambla.eu`)"
        - "traefik.http.routers.dakar-front.entrypoints=web"
        - "traefik.http.routers.dakar-front.middlewares=test-redirectscheme@docker"
        - "traefik.http.routers.dakar-ssl-front.rule=Host(`dakar.project.lambla.eu`)"
        - "traefik.http.routers.dakar-ssl-front.entrypoints=websecure"
        - "traefik.http.routers.dakar-ssl-front.tls=true"
        - "traefik.http.routers.dakar-ssl-front.tls.certresolver=myresolver"
        - "traefik.http.services.dakar-front.loadbalancer.server.port=80"

networks:
  dakar-network:
    driver: overlay
    external: false
  traefik_traefik:
    driver: overlay
    external: true

volumes:
  couch:
    driver: local
    driver_opts:
      type: none
      device: /opt/couchbase/node1/var
      o: bind
